nav:
    - Home: 'index.md'
    - Milestones:
        - One: 'milestone_one.md'
        - Two: 'milestone_two.md'
        - Three: 'milestone_three.md'

site_name: "Orb2019 - $TEAMNAME"
site_description: "Orb2019 - $TEAMNAME"
theme:
    name: gitbook

plugins: []

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
    - admonition
    - footnotes
    - pymdownx.superfences
    - pymdownx.arithmatex
    - pymdownx.caret
    - codehilite:
        linenums: True

extra_css:
    - 'stylesheets/extra.css'
    - 'https://use.fontawesome.com/releases/v5.3.1/css/all.css'
    - 'https://fonts.googleapis.com/css?family=Gentium+Book+Basic'
    - 'https://fonts.googleapis.com/css?family=Roboto:400,700'
